### ISSUE TITLE
Would you mind if I use your skin as default in MC Skin Editor?

### ISSUE THREAD

**Issue by phplego** [alexk7110/mc-electricblue256-skin#2]
Hello,
sorry for creating issue. I didn't find other way to contact with you.
I ported one tool for mc's skins, and I want to use your awesome theme in the list as default one. Would you mind? 

Also btw maybe this tool will help you to create more beautiful themes what would be really nice, love it :)

Skin editor:
https://phplego.github.io/mc/

Thanks

**Comment by alexk7110** [comment]
Of 'course not.. Well I'm glad you did it anyway since I saw your comment over a year later. Your app would have been major help when I was creating this skin. I will bookmark your page, it will come real handy next time.
